package co.edu.konradlorenz.view;

import javax.swing.*;

public class Admin extends javax.swing.JFrame {
    
    public Admin() {
        initComponents();
    }

    public JButton getBtnMenuActualizar() {
        return btnMenuActualizar;
    }
    public void setBtnMenuActualizar(JButton btnMenuActualizar) {
        this.btnMenuActualizar = btnMenuActualizar;
    }
    
    public JButton getBtnVolver() {
        return btnVolver;
    }
    public void setBtnVolver(JButton btnVolver) {
        this.btnVolver = btnVolver;
    }
    
    public JButton getBtnMenuAsignatura() {
        return btnMenuAsignatura;
    }
    public void setBtnMenuAsignatura(JButton btnMenuAsignatura) {
        this.btnMenuAsignatura = btnMenuAsignatura;
    }

    public JButton getBtnEliminar() {
        return btnEliminar;
    }
    public void setBtnEliminar(JButton btnEliminar) {
        this.btnEliminar = btnEliminar;
    }

    public JButton getBtnHecho() {
        return btnHecho;
    }
    public void setBtnHecho(JButton btnHecho) {
        this.btnHecho = btnHecho;
    }

    public JButton getBtnListar() {
        return btnListar;
    }
    public void setBtnListar(JButton btnListar) {
        this.btnListar = btnListar;
    }

    public JButton getBtnMenuInsertar() {
        return btnMenuInsertar;
    }
    public void setBtnMenuInsertar(JButton btnMenuInsertar) {
        this.btnMenuInsertar = btnMenuInsertar;
    }

    public JButton getBtnRegistrar() {
        return btnRegistrar;
    }
    public void setBtnRegistrar(JButton btnRegistrar) {
        this.btnRegistrar = btnRegistrar;
    }

    public JButton getBtnMenuUsuario() {
        return btnMenuUsuario;
    }
    public void setBtnMenuUsuario(JButton btnMenuUsuario) {
        this.btnMenuUsuario = btnMenuUsuario;
    }

    public JButton getBtnMenuUsuarioAsignatura() {
        return btnMenuUsuarioAsignatura;
    }
    public void setBtnMenuUsuarioAsignatura(JButton btnMenuUsuarioAsignatura) {
        this.btnMenuUsuarioAsignatura = btnMenuUsuarioAsignatura;
    }

    public JComboBox<String> getCbbCampo3() {
        return cbbCampo3;
    }
    public void setCbbCampo3(JComboBox<String> cbbCampo3) {
        this.cbbCampo3 = cbbCampo3;
    }

    public JLabel getLblCampo1() {
        return lblCampo1;
    }
    public void setLblCampo1(JLabel lblCampo1) {
        this.lblCampo1 = lblCampo1;
    }

    public JLabel getLblCampo2() {
        return lblCampo2;
    }
    public void setLblCampo2(JLabel lblCampo2) {
        this.lblCampo2 = lblCampo2;
    }

    public JLabel getLblTitulo() {
        return lblTitulo;
    }
    public void setLblTitulo(JLabel lblTitulo) {
        this.lblTitulo = lblTitulo;
    }

    public JPanel getPlRegistros() {
        return plRegistros;
    }
    public void setPlRegistros(JPanel plRegistros) {
        this.plRegistros = plRegistros;
    }

    public JTable getTblTabla() {
        return tblTabla;
    }
    public void setTblTabla(JTable tblTabla) {
        this.tblTabla = tblTabla;
    }

    public JTextField getTxtCampo2() {
        return txtCampo2;
    }
    public void setTxtCampo2(JTextField txtCampo2) {
        this.txtCampo2 = txtCampo2;
    }

    public JTextField getTxtCampo1() {
        return txtCampo1;
    }
    public void setTxtCampo1(JTextField txtCampo1) {
        this.txtCampo1 = txtCampo1;
    }

    public JButton getBtnConfirmar() {
        return btnConfirmar;
    }
    public void setBtnConfirmar(JButton btnConfirmar) {
        this.btnConfirmar = btnConfirmar;
    }

    public JLabel getLblCampo3Cbb() {
        return lblCampo3Cbb;
    }
    public void setLblCampo3Cbb(JLabel lblCampo3Cbb) {
        this.lblCampo3Cbb = lblCampo3Cbb;
    }

    public JScrollPane getSpnTabla() {
        return spnTabla;
    }
    public void setSpnTabla(JScrollPane spnTabla) {
        this.spnTabla = spnTabla;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnListar = new javax.swing.JButton();
        btnMenuInsertar = new javax.swing.JButton();
        btnMenuActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        spnTabla = new javax.swing.JScrollPane();
        tblTabla = new javax.swing.JTable();
        plRegistros = new javax.swing.JPanel();
        lblCampo1 = new javax.swing.JLabel();
        lblCampo2 = new javax.swing.JLabel();
        lblCampo3Cbb = new javax.swing.JLabel();
        txtCampo1 = new javax.swing.JTextField();
        txtCampo2 = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        cbbCampo3 = new javax.swing.JComboBox<>();
        btnHecho = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnMenuUsuario = new javax.swing.JButton();
        btnMenuAsignatura = new javax.swing.JButton();
        btnMenuUsuarioAsignatura = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setBackground(new java.awt.Color(51, 153, 255));
        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Gestión Educativa");
        lblTitulo.setOpaque(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnListar.setText("Listar");

        btnMenuInsertar.setText("Nuevo");

        btnMenuActualizar.setText("Actualizar");

        btnEliminar.setText("Eliminar");

        btnConfirmar.setText("Confirmar Selección");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMenuInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMenuActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConfirmar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListar)
                    .addComponent(btnMenuInsertar)
                    .addComponent(btnMenuActualizar)
                    .addComponent(btnEliminar)
                    .addComponent(btnConfirmar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Clave", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spnTabla.setViewportView(tblTabla);

        plRegistros.setBorder(javax.swing.BorderFactory.createTitledBorder("Registrar Usuario"));

        lblCampo1.setText("Nombre del Usuario: ");
        lblCampo1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCampo2.setText("Clave: ");
        lblCampo2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCampo3Cbb.setText("Tipo:");
        lblCampo3Cbb.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnRegistrar.setText("Registrar");

        btnHecho.setText("Hecho");

        javax.swing.GroupLayout plRegistrosLayout = new javax.swing.GroupLayout(plRegistros);
        plRegistros.setLayout(plRegistrosLayout);
        plRegistrosLayout.setHorizontalGroup(
            plRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plRegistrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plRegistrosLayout.createSequentialGroup()
                        .addComponent(lblCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCampo1))
                    .addGroup(plRegistrosLayout.createSequentialGroup()
                        .addComponent(lblCampo3Cbb, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbCampo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHecho, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 17, Short.MAX_VALUE))
                    .addGroup(plRegistrosLayout.createSequentialGroup()
                        .addComponent(lblCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCampo2)))
                .addContainerGap())
        );
        plRegistrosLayout.setVerticalGroup(
            plRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plRegistrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(plRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(plRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCampo3Cbb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbCampo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHecho)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnMenuUsuario.setText("Usuarios");

        btnMenuAsignatura.setText("Asignatuas");

        btnMenuUsuarioAsignatura.setText("Relaciones");

        btnVolver.setText("Volver");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMenuUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMenuAsignatura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMenuUsuarioAsignatura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMenuUsuario)
                    .addComponent(btnMenuAsignatura)
                    .addComponent(btnMenuUsuarioAsignatura)
                    .addComponent(btnVolver))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spnTabla)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(plRegistros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(plRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnHecho;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnMenuActualizar;
    private javax.swing.JButton btnMenuAsignatura;
    private javax.swing.JButton btnMenuInsertar;
    private javax.swing.JButton btnMenuUsuario;
    private javax.swing.JButton btnMenuUsuarioAsignatura;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cbbCampo3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCampo1;
    private javax.swing.JLabel lblCampo2;
    private javax.swing.JLabel lblCampo3Cbb;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel plRegistros;
    private javax.swing.JScrollPane spnTabla;
    private javax.swing.JTable tblTabla;
    private javax.swing.JTextField txtCampo1;
    private javax.swing.JTextField txtCampo2;
    // End of variables declaration//GEN-END:variables
}
